# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'LosGit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LosGit
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireObjectMapper', '~> 5.1'
  pod 'SDWebImage', '~> 5.0'
end
